# Generated by Django 3.1.7 on 2021-03-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210322_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-title']},
        ),
    ]
